### PR TITLE
Fix .template-env typo

### LINKED ISSUE #284: Fix typo
## Problem
.template-env is mentioned as .env-template in docs/README.md

### PR DESCRIPTION
**Pull request by ndharmateja**
Closes #284

### CODE REVIEW

**Comment by seporterfield** [comment]
Thanks for this!

**Review by seporterfield — APPROVED** [review]

**Comment by Monstarrrr** [comment]
Nice, also note that you don't have to mention which issue it closes because it's already referenced anyways in the branch name :)

**Comment by ndharmateja** [comment]
> Nice, also note that you don't have to mention which issue it closes in the issue body because it's already referenced anyways in the branch name and in the timelines :)

ah okay
i didn't know that, thanks!

so the issue will be auto closed without having to mention "closes"?

**Comment by Monstarrrr** [comment]
> > Nice, also note that you don't have to mention which issue it closes in the issue body because it's already referenced anyways in the branch name and in the timelines :)
> 
> ah okay i didn't know that, thanks!
> 
> so the issue will be auto closed without having to mention "closes"?

Only if on the PR you've mentioned the issue here
image

**Comment by ndharmateja** [comment]
> > > Nice, also note that you don't have to mention which issue it closes in the issue body because it's already referenced anyways in the branch name and in the timelines :)
> > 
> > 
> > ah okay i didn't know that, thanks!
> > so the issue will be auto closed without having to mention "closes"?
> 
> Only if on the PR you've mentioned the issue here, so doesn't matter how you do it actually image

ah okay!
thanks 👍🏼

**Pull request merged**
