### PR TITLE
Feat/93 ci backend tests

### PR DESCRIPTION
**Pull request by seporterfield**
#93

Created a flow for continuous integration checks, tests for the backend.
It also publishes the test results and OpenAPI schema.

This currently includes a linter/formatter check and unit tests.

### CODE REVIEW

**Comment by Monstarrrr** [comment]
I let @purple-void review this one

**Comment by seporterfield** [comment]
Linter fails right now, but that is only due to misconfig fixed by #133.

**Comment by purple-void** [comment]
We merged the latest code from main, including the code from [133](https://github.com/Monstarrrr/rebutify/pull/133), and the GitHub checks are still unsuccessful. The changes cannot be merged currently.

**Comment by seporterfield** [comment]
fixed previous pipeline errors :)

**Review by purple-void — APPROVED** [review]
Looks good

**Pull request merged**
